
# Start up SAMWeb, Nginx, SAM Station, and Apache
#

version: "3.7"
services:

    # Web server/reverse proxy/SSL termination
    apache:
        image: sam_httpd_server 
        ports:
            - "127.0.0.1:8483:8483"
            - "127.0.0.1:8480:8480"
        depends_on:
            - samweb_server
            - sam_station
            - sam_station_monitor
            - sam_landscape_stats
        volumes:
            - osg-ca-volume:/etc/grid-security/certificates

# SAM Monitoring Services
    # sam station monitor application server
    sam_station_monitor:
        image: sam_station_monitor
        volumes:
            - type: bind
              source: ./sam_monitoring/sam_station_monitor
              target: /opt/sam/sam-station-monitor

    # SAM Station Monitor Application Server
    sam_landscape_stats:
        image: sam_landscape_stats
        volumes:
            - type: bind
              source: ./sam_monitoring/sam_landscape_stats/sam_stats_graphite.py
              target: /sam_stats_graphite.py
            - type: bind
              source: ./sam_monitoring/sam_landscape_stats/db_read_password
              target: /db_read_password
        environment:
            - GRAPHITE_SERVER_HOST=fifemondata.fnal.gov
            - GRAPHITE_SERVER_PORT=2004
            - SAMDBS_PASSWORD_FILE=file:db_read_password

# SAM Main Services
    # SAM Web Server with DB password as a secret
    samweb_server:
        image: samweb_server
        ports:
            - "127.0.0.1:5555:5555"
        environment:
            - EXPERIMENT=sam_bjwhite
        volumes:
            - type: bind
              source: ./samweb_server/sam-web 
              target: /opt/sam/samweb_server/sam-web

        secrets:
            - samweb_db_secret


    # SAM Station
    sam_station:
        image: sam_station
        ports:
            - "127.0.0.1:4444:4444"
        #environment:
        #    - SAM_DCACHE_TEST=1
        volumes:
            - type: bind
              source: ./sam_station/sam-station
              target: /opt/sam/sam_station/sam-station
            - /tmp/x509up_u51660:/opt/sam/sam_station/station_proxy
            - ./sam_station/config/bjwhite_test_config.yaml:/opt/sam/sam_station/sam_station_config.yaml
            - ./sam_station/config/bjwhite_test_file_schema_mapping.json:/opt/sam/sam_station/file_schema_mapping.json
            - ./sam_station/config/bjwhite_test_location_map.yaml:/opt/sam/sam_station/location_map.yaml
              

    # Service to handle OSG CA Certificates by updating them and making them available via the named volume 'osg-ca-volume'
    osg_authentication:
        image: bjwhitefnal/osg_authentication
        volumes:
            - osg-ca-volume:/etc/grid-security/certificates
    
volumes:
    osg-ca-volume:
    
secrets:
    samweb_db_secret:
        file: ./samweb_server/config/secret/postgres.secret
