apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      serviceAccountName: useroot
      volumes:
      - name: server-hostcert
        secret:
          secretName: server-hostcert
      - name: server-hostkey
        secret:
          secretName: server-hostkey
      - name: db-database
        secret:
          secretName: db-database
      - name: db-hostname
        secret:
          secretName: db-hostname
      - name: db-port
        secret:
          secretName: db-port
      - name: db-pass
        secret:
          secretName: db-pass
      - name: ca-volume
        emptyDir: {}
      initContainers:
      - name: grid-certs
        image: docker.io/bjwhitefnal/grid-security-files:32
        command: ["/bin/bash", "-c", "chmod 755 /out/ && cp -rv --preserve=links /grid-certificates/* /out/"]
        volumeMounts:
        - name: ca-volume
          mountPath: /out/
      containers:
      - name: apache
        image: imageregistry.fnal.gov/sam-zerg/sam-httpd-server:latest
        ports:
        - containerPort: 8443
          name: https
        - containerPort: 8480
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: server-hostcert
          mountPath: /opt/sam/httpd/certs/server.crt
          subPath: server.crt
        - name: server-hostkey
          mountPath: /opt/sam/httpd/certs/server.key
          subPath: server.key
        - name: ca-volume
          mountPath: /etc/grid-security/certificates
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samweb-server
  labels:
    app: samweb-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samweb-server
  template:
    metadata:
      labels:
        app: samweb-server
    spec:
      serviceAccountName: useroot
      volumes:
      - name: db-database
        secret:
          secretName: db-database
      - name: db-hostname
        secret:
          secretName: db-hostname
      - name: db-port
        secret:
          secretName: db-port
      - name: db-pass
        secret:
          secretName: db-pass
      containers:
      - name: samweb-server
        image: imageregistry.fnal.gov/sam-zerg/samweb-server:latest
        ports:
        - containerPort: 3000
          name: uwsgi 
        env:
        - name: EXPERIMENT
          value: samdev
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-database
              key: db-database
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-hostname
              key: db-hostname
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-port
              key: db-port
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-pass
              key: db-pass
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"