apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    app: apache
spec:
  selector:
    app: apache
  ports:
  - name: http
    port: 8480
    targetPort: 8480
  - name: https
    port: 8483
    targetPort: 8483
  externalIPs: [ 131.225.218.183 ]
---
apiVersion: v1
kind: Service
metadata:
  name: samweb-server
  labels:
    app: samweb-server
spec:
  selector:
    app: samweb-server