apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 8480
    targetPort: 8480
  - name: https
    port: 8483
    targetPort: 8483
  - name: https-samweb
    port: 8484
    targetPort: 8484
  externalIPs: [ 131.225.218.233 ]
---
apiVersion: v1
kind: Service
metadata:
  name: samweb-server
  labels:
    app: samweb-server
spec:
  selector:
    app: samweb-server
  ports:
  - name: uwsgi
    port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sam-station
  labels:
    app: sam-station
spec:
  selector:
    app: sam-station
  ports:
  - name: uwsgi
    port: 21000
    targetPort: 21000
---
apiVersion: v1
kind: Service
metadata:
  name: sam-station-monitor
  labels:
    app: sam-station-monitor
spec:
  selector:
    app: sam-station-monitor
  ports:
  - name: uwsgi
    port: 8081
    targetPort: 8081
